### ISSUE TITLE
not working It does not work well ios ipad pro ios 18.2

### ISSUE THREAD

**Issue by popcorn2024ok** [Pomelo-Emu/pomelo-emu.github.io#19]
Hello, I have problems with grapefruit. I have iOS version 18.2 I have an iPad Pro and when I install the games, they close and do not load on grapefruit. Is there any configuration for grapefruit so that the Nintendo Switch ROM games load

Please can you send me the ipa that works and is stable

**Comment by TechGuy541** [comment]
Don't put issues here put them in the gitlab repo pls
